FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy backend files
COPY backend ./backend

# Expose port
EXPOSE 3001

# Set production env
ENV NODE_ENV=production

# Run command
CMD ["node", "backend/index.js"]
